### ISSUE TITLE
Supporting oauth

### ISSUE THREAD

**Issue by pjpsoares** [jira-node/node-jira-client#23]
Are you thinking on adding support for oauth?

**Comment by mtscout6** [comment]
We accept pull requests!

**Comment by pjpsoares** [comment]
:+1:

**Comment by pjpsoares** [comment]
Didn't had the chance to do this, but will try to make a pull request with this in the following week.

**Comment by attrib** [comment]
Just my 2 cents about the, as I just worked on the OAuth for node-jira. And were thinking about adding OAuth here now too, but stopped this now from my side. But at least I want to give some hints/concerns about stuff I found out, doing it for the original node-jira.

1. I like the Promise support, but the new code is for me much harder to read. Was there stuff auto-generated? (e.g. _asyncToGenerator3) [background info I'm new to ES6/ES7 and doesn't know babel]
2. request-promise has one big drawback from request module. I lacks support for OAuth, cookies, auth and a lot of other stuff. So either try to add it there or implement OAuth support here directly. request is using the oauth-sign module which I can recommend here, this takes care of the crypto stuff and rfc3986 url encoding. Atlassian Cloud only supports RSA-SHA1. 
3. Alternativly the oauth module could be used. But this has a own request library and you need to use bluebird or similar to promisfy it. So you ending up having different libraries to make a request and then a switch in `doRequest`. This will make it harder to maintain. Also next to the OAuth object the access token, access token request is needed. Also it seems there is a bug in the oauth module and for a get request you can't set the content-type. Jira doesn't support this. Needs to be checked before using it ;)

Gist about how to retrieve an access token over cli, which you can use afterwards: https://gist.github.com/attrib/ea446d5cd25617cf14a2

**Comment by mtscout6** [comment]
@attrib We use [Babel](http://babeljs.io/) to compile the ES7 JavaScript to ES5 for those using systems that don't support the newer version of JavaScript yet. The original source is in the `src` folder and the compiled output lands in the `lib` folder. The `_asyncToGenerator3` function you are seeing is a result of that compilation step. I think you'll find the stuff in the `src` folder much easier to read.

`request-promise` Is  just a thin wrapper around `request` that wraps the callback style functions with a Promise based signature. So, every function that's on `request` is in `request-promise`, the only difference is that you don't need to provide callback functions. All the functions should be the same otherwise. If that is not the case then it should be taken up with `request-promise`, which is maintained by the same guys as `request`.

**Comment by attrib** [comment]
@mtscout6 Thansk for the explantion. Now I got it and could do it quickly.
Thanks.

**Comment by KanoYugoro** [comment]
PR #27 got in and I did a major version release, so we should now be supporting oauth.

**Comment by Meaglin** [comment]
Jira still does not work, i had to switch to https://github.com/sladey/node-oauth to make it work.

**Comment by Gby56** [comment]
@attrib sorry for digging this up but I'm really confused to how the OAuth is implemented here, I don't see any signature function calls etc... Is this implemented fully ? I saw the Bearer Token was

**Comment by Gby56** [comment]
For people confused maybe on how to use the OAuth options, and why it's not fully documented here, it's handled by request-promise directly
https://github.com/request/request#requestoptions-callback
https://github.com/request/request#oauth-signing
