### ISSUE TITLE
client.updateIssue produces undefined response on successful operations

### ISSUE THREAD

**Issue by matthewvandergrift** [jira-node/node-jira-client#307]
Whether I perform A or B, I do not get a response on jira actions that are being completed successfully.

A
client.updateIssue(this.request.issueId, issueObject).then(resp => {// dosomething });

or B:
const response = await this.client.updateIssue(this.request.issueId, issueObject);

**Comment by randyho-kk** [comment]
how are you setting up the client?  
what are you passing in for this.request.issueId and issueObject?

**Comment by pioug** [comment]
@matthewvandergrift Hmm, what do you expect because the documentation mentions `204 No Content` when successful.

https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/#api-rest-api-3-issue-issueidorkey-put
![image](https://user-images.githubusercontent.com/3654180/94964276-1ee5ab00-052c-11eb-86b4-e572f6095bdd.png)

See if you can `catch` something maybe. But in any case, `updateIssue` follows the same pattern as every other method, so it's not hiding the response.
